name: trabajo_final
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  getwidget: ^4.0.0
  http: ^1.2.2
  provider: ^6.1.2
  url_launcher: ^6.1.5
  flutter_native_splash: ^2.3.7
  dio: ^5.4.3+1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.3.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  image: "assets/icons/logo.png"
  color: "#252829"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
